language: python
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade numpy  coverage pytest pytest-cov cython codecov
- python setup.py install

script:
- python -m pytest -vv --cov=rainbowpy/
#- codecov --token=2adee64a-60b0-4c7e-b94c-512ea2b8e794

  on:
    tags: true
  distributions: "sdist bdist_wheel" # Your distributions here
  skip_existing: true
